name: Free Windows RDP (Cloudflare Tunnel)

on: workflow_dispatch

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Setup RDP User
      run: |
        net user githubRDP MyPassword123! /add
        net localgroup administrators githubRDP /add
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download Cloudflare Tunnel
      run: |
        Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

    - name: Start Tunnel
      run: |
        Start-Process -NoNewWindow -FilePath ".\cloudflared.exe" -ArgumentList "tunnel --url tcp://localhost:3389 --no-autoupdate --logfile cloudflared.log"
        Start-Sleep -Seconds 30
        Get-Content cloudflared.log

    - name: Save Tunnel Info
      uses: actions/upload-artifact@v4
      with:
        name: tunnel-log
        path: cloudflared.log
